Fix lint errors in Rust 1.73 and 1.74 (#155)
Fixes the following which are new in Rust 1.73:

```
error: use of `or_insert_with` to construct default value
  --> src/changelog.rs:53:38
   |
53 | ...                   .or_insert_with(Vec::new);
   |                        ^^^^^^^^^^^^^^^^^^^^^^^^ help: try: `or_default()`
   |
   = help: for further information visit https://rust-lang.github.io/rust-clippy/master/index.html#unwrap_or_default
   = note: `-D clippy::unwrap-or-default` implied by `-D warnings`

error: use of `or_insert_with` to construct default value
  --> src/changelog.rs:63:26
   |
63 |                         .or_insert_with(Vec::new);
   |                          ^^^^^^^^^^^^^^^^^^^^^^^^ help: try: `or_default()`
   |
   = help: for further information visit https://rust-lang.github.io/rust-clippy/master/index.html#unwrap_or_default
```

And these from Rust 1.74 (only showing first error):

```
warning: unnecessary hashes around raw string literal
   --> src/changelog.rs:140:13
    |
140 | /             r#"
141 | | # Changelog
142 | |
143 | | All notable changes to this project will be documented in this file.
...   |
146 | | and this project adheres to [Semantic Versioning](https://semver.org/spec/v2.0.0.html).
147 | |         "#
    | |__________^
    |
    = help: for further information visit https://rust-lang.github.io/rust-clippy/master/index.html#needless_raw_string_hashes
...
```

GUS-W-14249468.