Fix classic buildpack prepare release workflow (#192)
Currently if the `git log` generated to populate the PR description
contains more than one commit, the workflow fails with errors like:

```
Error: Unable to process file command 'output' successfully.
Error: Invalid format '- Migrate from CircleCI to GHA (#214)'
```

This is because of the GitHub Actions gotcha around multi-line
strings when using `GITHUB_OUTPUT` (or `GITHUB_ENV`):
https://docs.github.com/en/actions/using-workflows/workflow-commands-for-github-actions#multiline-strings

This didn't come up during testing, since the repo I tried with
didn't have multiple commits on `main` since the last tag.

See also:
https://github.com/heroku/heroku-buildpack-nodejs/pull/1153
https://github.com/heroku/libcnb.rs/pull/692

GUS-W-14894410.